### ISSUE TITLE
Case where recruitment in 1 season and season != 1

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#30]
Hi,

My model is failing in the ASPG function call because the model is season and recruitment occurs in season 2 only. In this case, age 1 of the biol in season 1 remain an NA and line 110 of OM_1a_Population_Growth_Functions.R 

```
 if(any(biol@n[,yr,,ss]<0)){
```
cannot be evaluated (<0 on an NA).

It looks that previously this was addressed on line 110:
#   biol@n[1,yr,,ss] <- 0

Can this be reinstated or should I only have SRs that contain 1 season (season 2, mine currently include all seasons, but prop = 0 in 1,3 and 4) ?

Thanks

**Comment by pdolder** [comment]
I don't know why that writing is giant, I didn't do that!

**Comment by ssanchezAZTI** [comment]
Dear Paul,

The problem is exclusively for the first season, as for the rest, if there is not recruitment, numbers are taken from the previous season.
I did the following change and uploaded to GitHub:

} else if (ss==1) { # If the recruitment season is NOT the first one, set recruits value to 0 in this season.
    biol@n[1,yr,,ss] <- 0
} # If the recruitment season is NOT the first one, do nothing, the population in first age group is just the survivors of previous season.

I think now should work! If not please make us notice.

Sonia

De: Paul Dolder <notifications@github.com>
Enviado el: jueves, 07 de marzo de 2019 13:52
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [flr/FLBEIA] Case where recruitment in 1 season and season != 1 (#30)


Hi,

My model is failing in the ASPG function call because the model is season and recruitment occurs in season 2 only. In this case, age 1 of the biol in season 1 remain an NA and line 110 of OM_1a_Population_Growth_Functions.R

 if(any(biol@n[,yr,,ss]<0)){

cannot be evaluated (<0 on an NA).

It looks that previously this was addressed on line 110:

biol@n[1,yr,,ss] <- 0

Can this be reinstated or should I only have SRs that contain 1 season (season 2, mine currently include all seasons, but prop = 0 in 1,3 and 4) ?

Thanks

**Comment by pdolder** [comment]
Hi Sonia,

That should fix it. However, you changed ASPG_Baranov and it also needs to be changed in ASPG (line 104) ?

Thanks

**Comment by ssanchezAZTI** [comment]
You are right! I’ve seen that you already uploaded the change to GitHub.

Thank you very much!
Sonia

De: Paul Dolder <notifications@github.com>
Enviado el: jueves, 07 de marzo de 2019 14:55
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Sonia Sanchez <ssanchez@azti.es>; Comment <comment@noreply.github.com>
Asunto: Re: [flr/FLBEIA] Case where recruitment in 1 season and season != 1 (#30)


Hi Sonia,

That should fix it. However, you changed ASPG_Baranov and it also needs to be changed in ASPG (line 104) ?

Thanks

**Comment by pdolder** [comment]
Yes, fixed there also - thanks!
Paul
