### ISSUE TITLE
F_flbeia error

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#31]
Hi,

I have just started encountering an error in F_flbeia when calling the bioSum function. It can be traced to line 92
https://github.com/flr/FLBEIA/blob/d14832d18e61fb411bc0e93f936e43bf0e12f035/R/Results_Summary.R#L92

When the function is applied to an FLBiol where some years of the n. are filled with NA (i.e. a stock with a shorter time series, but has been expanded to the length of the stock with the longest time series) then if (n.[a, y, ss, i] == 0) returns NA, so the function fails as a "missing value where TRUE/FALSE needed".

This makes sense but it did not happen in the past, and I can't see how the recent changes to F_flbeia could of caused it...?  Maybe its because I am using different package versions on a new computer,...but I think it should be OK to have NAs in the biol@n ?

Thanks,
Paul

**Comment by dorleta** [comment]
Hi Paul,

It has always given an error…. I don’t know why you did not get it in the past.

If you want to avoid the error you can use years argument in the call to the function and  select only those years that are empty of NA-s.

We are now in the process of changing all the summaries to dplyr and we can change it so it returns an NA when there is and NA instead of crashing.

Thanks Paul,

Dorleta


De: Paul Dolder <notifications@github.com>
Enviado el: 05 June 2019 14:02
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [flr/FLBEIA] F_flbeia error (#31)


Hi,

I have just started encountering an error in F_flbeia when calling the bioSum function. It can be traced to line 92
https://github.com/flr/FLBEIA/blob/d14832d18e61fb411bc0e93f936e43bf0e12f035/R/Results_Summary.R#L92

When the function is applied to an FLBiol where some years of the n. are filled with NA (i.e. a stock with a shorter time series, but has been expanded to the length of the stock with the longest time series) then if (n.[a, y, ss, i] == 0) returns NA, so the function fails as a "missing value where TRUE/FALSE needed".

This makes sense but it did not happen in the past, and I can't see how the recent changes to F_flbeia could of caused it...? Maybe its because I am using different package versions on a new computer,...but I think it should be OK to have NAs in the biol@n ?

Thanks,
Paul

**Comment by dorleta** [comment]
Hi Paul,

You were right at some point we add an ‘if’ to avoid problems when ‘n’ was 0 and the problem with NA-s arose.

I’ve solved the problem and upload the updated code to GitHub.

Cheers,

Dorleta


De: Paul Dolder <notifications@github.com>
Enviado el: 05 June 2019 14:02
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [flr/FLBEIA] F_flbeia error (#31)


Hi,

I have just started encountering an error in F_flbeia when calling the bioSum function. It can be traced to line 92
https://github.com/flr/FLBEIA/blob/d14832d18e61fb411bc0e93f936e43bf0e12f035/R/Results_Summary.R#L92

When the function is applied to an FLBiol where some years of the n. are filled with NA (i.e. a stock with a shorter time series, but has been expanded to the length of the stock with the longest time series) then if (n.[a, y, ss, i] == 0) returns NA, so the function fails as a "missing value where TRUE/FALSE needed".

This makes sense but it did not happen in the past, and I can't see how the recent changes to F_flbeia could of caused it...? Maybe its because I am using different package versions on a new computer,...but I think it should be OK to have NAs in the biol@n ?

Thanks,
Paul

**Comment by pdolder** [comment]
Hi Dorleta,

Thanks, that's working again now.

Paul
