### ISSUE TITLE
Bug in "overfishing"

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#38]
Hi,

I am encountering a bug in the function "overfishing" where I get:

```{r}
Error in f[x, , ] : incorrect number of dimensions
```

It looks that this is because F_flbeia returns an object with different dims ?

```{r}
res[stk,,,] <- apply(aux,2:4,mean) 
```

https://github.com/flr/FLBEIA/blob/c4451c7f80f017976cd64b5f74d80095fceb0b26/R/Results_Summary.R#L104 

So its inconsistent, I think ?

Paul

**Comment by dorleta** [comment]
Hi,

Exactly. In the last revision of the summary functions we made them all seasonal for consistency so now fishing mortality is calculated by season, but we didn’t update overfishing. I’ve fixed the bug now,

Thanks!!

Dorleta


De: Paul Dolder <notifications@github.com>
Enviado el: Thursday, 18 June 2020 17:04
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [flr/FLBEIA] Bug in "overfishing" (#38)


Hi,

I am encountering a bug in the function "overfishing" where I get:

Error in f[x, , ] : incorrect number of dimensions

It looks that this is because F_flbeia returns an object with different dims ?

res[stk,,,] <- apply(aux,2:4,mean)

https://github.com/flr/FLBEIA/blob/c4451c7f80f017976cd64b5f74d80095fceb0b26/R/Results_Summary.R#L104<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflr%2FFLBEIA%2Fblob%2Fc4451c7f80f017976cd64b5f74d80095fceb0b26%2FR%2FResults_Summary.R%23L104&data=02%7C01%7C%7Cb75eda775d2e48217a9208d81398e143%7C6219f1193e794e7facdea5750808cd9b%7C0%7C0%7C637280894640552822&sdata=BKxBRdQ%2F5XabPp7wF77eHcY25lG181F37IHWO9HViUA%3D&reserved=0>

So its inconsistent, I think ?

Paul

**Comment by pdolder** [comment]
Hi Dorleta,

I don't think you pushed this change to master?

Thanks!
Paul

**Comment by dorleta** [comment]
Hi,

Try now, I think I committed but didn’t push,

Dorleta


De: Paul Dolder <notifications@github.com>
Enviado el: Monday, 22 June 2020 15:57
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Dorleta Garcia <dgarcia@azti.es>; Comment <comment@noreply.github.com>
Asunto: Re: [flr/FLBEIA] Bug in "overfishing" (#38)


Hi Dorleta,

I don't think you pushed this change to master?

Thanks!
Paul

**Comment by pdolder** [comment]
Hi Dorleta,

This has fixed, but it now has another bug further down the line.... 

In the QuotaSwap function, `rho' is passed to CobbDouglasAge (or whatever), and it passed rho[st], but this now returns an NA. Should be rho[st,] ?

Paul

**Comment by dorleta** [comment]
Exactly, changed in github, thanks!

De: Paul Dolder <notifications@github.com>
Enviado el: Wednesday, 24 June 2020 10:20
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Dorleta Garcia <dgarcia@azti.es>; Comment <comment@noreply.github.com>
Asunto: Re: [flr/FLBEIA] Bug in "overfishing" (#38)


Hi Dorleta,

This has fixed, but it now has another bug further down the line....

In the QuotaSwap function, `rho' is passed to CobbDouglasAge (or whatever), and it passed rho[st], but this now returns an NA. Should be rho[st,] ?

Paul

**Comment by pdolder** [comment]
All good, eskerrik asko!
