### ISSUE TITLE
Have year as 'Gregorian year' not data+simulation year

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#44]
Hi,

Really a suggestion than an enhancement. When the simulations are running the information provided is the data+simulation year 1 -> end simulation year.

It would be good if either instead or additionally the Gregorian year is printed. Personally I tend to know the year range I've set for the simulation (i.e. 2020 -> 2030), but don't intuitively know how many years since the first data year.

**Comment by dorleta** [comment]
You are right Paul, I’ve uploaded the update to github, I don’t know why we have not done it earlier,

Dorleta


De: Paul Dolder <notifications@github.com>
Enviado el: Tuesday, 21 July 2020 13:04
Para: flr/FLBEIA <FLBEIA@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [flr/FLBEIA] Have year as 'Gregorian year' not data+simulation year (#44)


Hi,

Really a suggestion than an enhancement. When the simulations are running the information provided is the data+simulation year 1 -> end simulation year.

It would be good if either instead or additionally the Gregorian year is printed. Personally I tend to know the year range I've set for the simulation (i.e. 2020 -> 2030), but don't intuitively know how many years since the first data year.

**Comment by pdolder** [comment]
Thanks!
