### ISSUE TITLE
totvcost_flbeia 

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#51]
Hi,

This may be a false alarm so apologies if so, but I have seen some strange behaviour in using the totvcost_flbeia function.

Specifically, this part returns res as zeros:

    res <- FLQuant(0, dimnames = dimnames(fleet@effort))
    for (mt in mts) {
        res <- res + fleet@metiers[[mt]]@vcost * fleet@effort * 
            fleet@metiers[[mt]]@effshare
    }

Even though, if I choose an individual metier :
fleet@metiers[[mt]]@vcost * fleet@effort * 
            fleet@metiers[[mt]]@effshare

It does not have zero values. Something about adding res + a new FLQuant seems to be having odd behaviour.

As a result, which is being returned from the function is only this bit:
    Rev <- revenue_flbeia(fleet) * fleet@crewshare
 
Not the full variable costs..

Maybe something to check?  

Happy to learn it is just me!

Paul

**Comment by pdolder** [comment]
A solution (if this problem exists!) would be to do this step in an lapply and Reduce, which works for me.

**Comment by pdolder** [comment]
Apologies, this error only seems to occur for me when in the debug -- otherwise it seems to work fine. Am closing.

**Comment by marchtaylor** [comment]
I also have noticed some strange behaviour with these functions. This might be the reason. Also, I recommend that if there is no `covars[["NumbVessels"]]`, this should be set to a FLQuant with only ones (not zeroes, as it is in flSum). This gets used in the fcost calculation, and results in zero fixed costs when not defined.

**Comment by marchtaylor** [comment]
Ah... OK, wasn't a real issue. In any case be careful when you don't have covars...

**Comment by dorleta** [comment]
Hi,

Happy to check the functions if there is a problem, but it seems it was something related with your case study Paul?

Using Reduce and lapply would be definitively more elegant, but couldn't solve the problem with NAs because it does not allow the argument na.rm = TRUE. Although, I think if there is an NA in some metier is better to return NA, because it is a way to advice about a missing value in the conditioning,

Best,

Dorleta


De: Marc Taylor ***@***.***>
Enviado el: Monday, 29 March 2021 12:55
Para: flr/FLBEIA ***@***.***>
CC: Subscribed ***@***.***>
Asunto: Re: [flr/FLBEIA] totvcost_flbeia (#51)


Ah... OK, wasn't a real issue. In any case be careful when you don't have covars...

-

**Comment by pdolder** [comment]
Hi both,

I think it was not so much my case study as it was an issue when I was
running the function within debug. I need to check this further, but the
response seemed to be correct when calling the function overall.

Dorleta - I see the point about using lapply and Reduce not allowing na.rm
= TRUE, in this case it's such a short runtime I can't see doing it in a
loop as you have really causes as runtime issues.

Paul
