### ISSUE TITLE
Problem with IcesHCR

### ISSUE THREAD

**Issue by pdolder** [flr/FLBEIA#61]
Hi,

Tagging in @marchtaylor , @dorleta @pacematt.

Marc-  you made some changes recently to IcesHCR as there was some issue with how it was operating. Have you tested this running on more than a single iteration?  I think I can see some problems here, as when I tried it it threw back an error.

1.  Previous code picked up the particular iteration of Ftg running in a loop, i.e.

    if(int.yr == 'Fsq')
            fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1),  val = c(1, Ftg[i]), quantity = c( 'f', 'f'), rel.year = c(-1,NA)))
        else
            fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1),  val = c(advice$TAC[stknm,year, drop=TRUE][i], Ftg[i]), quantity = c( 'catch', 'f')))

However, your code removes this:

 if(int.yr == 'Fsq')
            fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1),  val = c(1, Ftg), quantity = c( 'f', 'f'), rel.year = c(-1,NA)))
        else
            fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1),  val = c(advice$TAC[stknm,year, drop=TRUE][i], Ftg), quantity = c( 'catch', 'f')))

Ftg is defined as:

    # For Ftg we first use Fmsy and then rerun fwd using the updated Ftg depending on the value of SSB
        Ftg <- ref.pts['Fmsy',]

Maybe it just needs to be ref.pts['Fmsy',i]  ??

**Comment by pdolder** [comment]
I should say the error was:

Error in h(simpleError(msg, call)) :
error in evaluating the argument 'object' in selecting a method for function 'fwdControl': arguments imply differing number of rows: 2, 101

So it looks simply like Ftg is the wrong dimensions now.

**Comment by pdolder** [comment]
It was this, so I fixed, tested and merged the fix. Hope that's ok.

**Comment by marchtaylor** [comment]
Thanks Paul

**Comment by pdolder** [comment]
Hi,

Me again. I've spotted something else I'm not too sure about...

Here:             
fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1),  val = c(1, Ftg), quantity = c( 'f', 'f'), rel.year = c(-1,NA)))
(https://github.com/flr/FLBEIA/blob/d0748c8ae5a4c46a6a1ff7758f797d3e284a7782/R/MP_3c_HCR_ICES_MSY.R#L82)

The control object is set up so that Fsq relates to the last years F irrespective of what you pass to fbar.nyears. I'm not sure if this was intended, but I would think it should relate to however you've set up your stf object...so in this case, it should be:

fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1),  val = c(1, Ftg), quantity = c( 'f', 'f'), rel.year = c(year,NA)))

As you have already set up the STF object with the F relating to the fbar.yrs and f.scale choices...

Checking you agree before I make the change.

**Comment by marchtaylor** [comment]
Yes, I think this makes sense. What is the default value used currently for fbar.yrs?

**Comment by pdolder** [comment]
3 years

**Comment by dorleta** [comment]
Hi,

Not sure about the correction proposed by Paul:

fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1), val = c(1, Ftg), quantity = c( 'f', 'f'), rel.year = c(year,NA)))

Having -1 was intented. You can't use 'year' because using -1,0,1 relates to the fact that it will be used in the projection so you can't use a year value. 0 means the intermediate year, -1 the data year, 1 advive year and so on. 

fbar.yrs is used to calculate the selection pattern. so as it is now, the HCR calculates the selection pattern using fbar.yrs and then the value is rescaled to the last year value. Usually we would like to use the mean value in the last fbar.yrs too, so then we would need something like:

Fsq <- mean(fbar(stk)[y1:y2]
fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1), val = c(Fsq, Ftg), quantity = c( 'f', 'f'), rel.year = c(NA,NA)))

where y1:y2 are the right years,

Best,

Dorleta

**Comment by pdolder** [comment]
Hi Dorleta,

A named year should work, or at least that's how we've been using it in the FCube code all these years... but equally I guess it could be rel.year = c(0,NA). Alternatively, given your suggestion should we include:

if(fbar.nyears | f.rescale) {
Fsq <- mean(fbar(stk)[,(year-1)])
} else {
Fsq <- mean(fbar(stk)[,(year-fbar.nyears):(year-1)]
}
fwd.ctrl <- FLash::fwdControl(data.frame(year = c(0, 1), val = c(Fsq, Ftg), quantity = c( 'f', 'f'), rel.year = c(NA,NA)))

**Comment by dorleta** [comment]
Hi Paul,

I agree with your suggestion,

Just as an explanation, 

 Fcube  works with named years because it is not running a long term simulation, it is applied just once. However, in FLBEIA when we run long term simulations the year numbers are updated in every year of the simulation, so the current year "yc" is sum up to the values in the fwdControl so we get the correct numbers, using -1, 0, 1...  is the reference to be used in the projections to get (yc-1, yc, yc+1) for example. 

Thanks!

Dorleta

**Comment by pdolder** [comment]
OK, change made and pushed.
